nameOverride: ""
fullnameOverride: ""
extraLabels:
  - app: PROJECT_KEY
  - env: infra-dev
crnamespace: openshift-gitops
app:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  type: helm
  helm:
    chart: helm-infra
    url: http://20.118.83.132:8081/repository/helm/
    revision: 0.0.5
    values:
      serviceAccount:
        create: true
        annotations: {}
        name: "portales"
        namespace: PROJECT_KEY
        local: true
      project:
        create: "true"
        name: "PROJECT_KEY"
        display: "PROJECT_DESCRIPTION"
        privileged: "true"
      bindings:
        create: "true"
        list:
        - name: secret-create
          namespace: PROJECT_KEY
          local: true
          extraLabels: 
            app: k8s-secrets-store
          subjects:
          - kind: ServiceAccount
            name: secrets-store-csi-driver
            namespace: k8s-secrets-store-csi
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: secret-create
    params:
      - name: secrets.create
        value: "true"
      - name: secrets.list[0].name
        value: azure-cr
      - name: secrets.list[0].namespace
        value: PROJECT_KEY
      - name: secrets.list[0].assignSecret
        value: "false"
      - name: secrets.list[0].assignPull
        value: "true"
      - name: secrets.list[0].type
        value: kubernetes.io/dockerconfigjson
      - name: 'secrets.list[0].data.\.dockerconfigjson'
        value: %JAR_AZURE_CR_DOCKERCONFIG_DEV%
        forceString: true