nameOverride: ""
fullnameOverride: ""
extraLabels:
  - app: folio-pago-services
  - env: dev
  - component: backend
crnamespace: openshift-gitops
app:
  destination:
    namespace: folio-pago
    server: 'https://kubernetes.default.svc'
  project: default
  type: helm
  autosync: true
  helm:
    chart: portales
    url: http://20.118.83.132:8081/repository/helm/
    revision: 0.1.11
    values:
        nameOverride: ""
        routeHostOverride: folio-pago-dev.apps.oxzaromdp01.southcentralus.aroapp.io
        routePathPrefix: /foliopagoapiV2
        # livenessProbe: 
        #   tcpSocket:
        #     port: 8080
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 20
        #   periodSeconds: 10
        #   successThreshold: 1
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /botonapiV2/actuator/health
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 20
        #   periodSeconds: 30
        #   successThreshold: 1
        #   failureThreshold: 3
        envFrom:
        - secretRef:
            name: folio-pago-services-secrets
        image:
          repository: oxzacrmdps01.azurecr.io/oxzacrmdps01/folio-pago-services
        replicaCount: 1
        serviceAccount:
          name: "default"
        extraLabels:
          - app.openshift.io/runtime: spring-boot
          - app.kubernetes.io/part-of: folio-pago-services
          - app.openshift.io/part-off: folio-pago-services
          - portal: folio-pago
          - env: dev
          - component: backend
        containerVolumes:
          create: true
          list:
          - type: inline-secret-store
            name: secrets-store-inline
            readOnly: true
            path: /mnt/secrets-store
            secretProviderClass: pb-azure-kv
            secretProviderCreds: folio-pago-services-store-creds
        configmaps:
          list: []
        secrets:
          create: true
          createProvider: true
          list: []
          providerRefs:
          - objName: OXZKVSD-FP-FCIAS-JDBC
            key: FCIAS_JDBC
          - objName: OXZKVSD-FP-FCIAS-PFPDAS-USR
            key: FCIAS_FP_USR
          - objName: OXZKVSD-FP-FCIAS-PFPDAS-PASS
            key: FCIAS_FP_PASS
          - objName: OXZKVSD-FP-POOL-SIZE-MAX
            key: POOL_SIZE_MAX
          - objName: OXZKVSD-FP-IDLE-MIN
            key: IDLE_MIN
          - objName: OXZKVSD-FP-IDLE-TIMEOUT
            key: IDLE_TIMEOUT
          - objName: OXZKVSD-FP-CONNECTION-TIMEOUT
            key: CONNECTION_TIMEOUT
          - objName: OXZKVSD-FP-LIFETIME-MAX
            key: LIFETIME_MAX
          - objName: OXZKVSD-FP-SERVER-SMTP
            key: SERVER_SMTP
          - objName: OXZKVSD-FP-HIKARI-DRIVER
            key: HIKARI_DRIVER
          - objName: OXZKVSD-FP-SWAGGER-ENABLED
            key: SWAGGER_ENABLED
          - objName: OXZKVSD-FP-SECURITY-URL
            key: SECURITY_URL
          providerSecretName: folio-pago-services-secrets
          providerKeyvaultName: OXZKVMDPD01
          providerClassName: pb-azure-kv
        imagePullSecrets:
          create: true
          list: 
          - name: azure-cr
        resources: 
          limits:
            cpu: "1"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "4Gi"
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 3
          targetMemoryUtilizationPercentage: 80
