app:
  helm:
    params:
      - name: secrets.list[0].name
        value: ips-secrets-store-creds
      - name: secrets.list[0].type
        value: Opaque
      # - name: 'secrets.list[0].extraLabels.secrets-store.csi.k8s.io/used'
      #   value: "true"
      - name: secrets.list[0].stringData.clientid
        value: %JAR_AZURE_KEYVAULT_CLIENTID_DEV%
      - name: secrets.list[0].stringData.clientsecret
        value: %JAR_AZURE_KEYVAULT_CLIENTSECRET_DEV%
      - name: secrets.providerTenant
        value: %JAR_AZURE_KEYVAULT_TENANTID_DEV%