nameOverride: ""
fullnameOverride: ""
extraLabels:
  - app: portal-mdm
  - env: dev
  - component: backend
crnamespace: openshift-gitops
app:
  destination:
    namespace: rec-hum
    server: 'https://kubernetes.default.svc'
  project: default
  type: helm
  autosync: true
  helm:
    chart: portales
    url: http://20.118.83.132:8081/repository/helm/
    revision: 0.1.9
    values:
      nameOverride: "portal-mdm-backend-dev"
      routeHostOverride: portal-mdm-backend-dev-rec-hum.apps.oxzaromdp01.southcentralus.aroapp.io
      # horizontalPodAutoscaler:
      #   create: true
      #   minReplicas: 2
      #   maxReplicas: 4
      #   metrics:
      #   - type: Resource
      #     resource:
      #       name: cpu
      #       target:
      #         averageUtilization: 70
      #         type: Utilization
      livenessProbe: 
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      readinessProbe:
          httpGet:
            path: /v3/api-docs
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
      env:
        - name: PORTAL_VERSION
          valueFrom:
            configMapKeyRef:
              name: mdm-configmap
              key: PORTAL_VERSION
        - name: AC_URL_BACK
          valueFrom:
            secretKeyRef:
              key: AC_URL_BACK
              name: portal-mdm-secret
        - name: MDM_APPID
          valueFrom:
            secretKeyRef:
              key: MDM_APPID
              name: portal-mdm-secret
        - name: FPORH_JDBC
          valueFrom:
            secretKeyRef:
              name: portal-mdm-secret
              key: FPORH_JDBC
        - name: FPORH_MDM_PASS
          valueFrom:
            secretKeyRef:
              name: portal-mdm-secret
              key: FPORH_MDM_PASS
        - name: FPORH_MDM_USER
          valueFrom:
            secretKeyRef:
              name: portal-mdm-secret
              key: FPORH_MDM_USER
        - name: MDM_URL_FRONT
          valueFrom:
            secretKeyRef:
              name: portal-mdm-secret
              key: MDM_URL_FRONT
      image:
        repository: oxzacrmdps01.azurecr.io/oxzacrmdps01/mdm-back
      replicaCount: 2
      serviceAccount:
        name: "portales"
      extraLabels:
        - app.openshift.io/runtime: spring-boot
        - app.kubernetes.io/part-of: portal-mdm
        - app.openshift.io/part-off: portal-mdm
        - portal: portal-mdm
        - env: dev
        - component: backend
      containerVolumes:
        create: true
        list:
        - type: inline-secret-store
          name: secrets-store-inline
          readOnly: true
          path: /mnt/secrets-store
          secretProviderClass: mdm-azure-kv
          secretProviderCreds: mdm-secrets-store-creds
      secrets:
        create: true
        createProvider: true
        list: []
        providerRefs:
        - objName: OXZKVSD-AC-URL-BACK
          key: AC_URL_BACK
        - objName: OXZKVSD-MDM-APPID
          key: MDM_APPID
        - objName: OXZKVSD-FPORH-JDBC
          key: FPORH_JDBC
        - objName: OXZKVSD-FPORH-MDM-PASS
          key: FPORH_MDM_PASS
        - objName: OXZKVSD-FPORH-MDM-USER
          key: FPORH_MDM_USER
        - objName: OXZKVSD-MDM-URL-FRONT
          key: MDM_URL_FRONT
        providerSecretName: portal-mdm-secret
        providerKeyvaultName: OXZKVMDPD01
        providerClassName: mdm-azure-kv