
nameOverride: ""
fullnameOverride: ""
extraLabels:
  - env: dev
crnamespace: openshift-gitops
app:
  destination:
    namespace: admin-fin
    server: 'https://kubernetes.default.svc'
  project: default
  type: helm
  helm:
    chart: portales
    url: http://20.118.83.132:8081/repository/helm/
    revision: 0.1.9
    values:
        nameOverride: "monitoror"
        routeHostOverride: monitoror-admin-fin.apps.oxzaromdp01.southcentralus.aroapp.io
        image:
          repository: oxzacrmdps01.azurecr.io/monitoror
        replicaCount: 1
        livenessProbe: 
            tcpSocket:
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        readinessProbe: 
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        serviceAccount:
          name: "default"
        
        extraLabels:
          - portal: monitoror
          - env: dev
        containerVolumes:
          create: true
          list:
          - name: monitoror-config
            type: configmap
            mode: "0775"
            path: /app/config
            readOnly: 'true'
        configmaps:
          create: true
          list:
          - name: monitoror-config
            data:
              config.json: |
                {
                  "version": "2.0",
                  "columns": 6,
                  "tiles": [
                    {
                      "type": "HTTP-STATUS",
                      "label": "Personas Bloqueadas Backend Dev DB",
                      "params": {
                        "url": "http://pb-back-dev-argo-app-lista-personas-bloqueadas-backend-dev.admin-fin.svc.cluster.local:8080/rest/v1/health/status"
                      }
                    },
                    {
                      "type": "HTTP-RAW",
                      "label": "Personas Bloqueadas Backend Dev API Doc",
                      "params": {
                        "url": "http://pb-back-dev-argo-app-lista-personas-bloqueadas-backend-dev.admin-fin.svc.cluster.local:8080/v3/api-docs"
                      }
                    },
                    {
                      "type": "HTTP-STATUS",
                      "label": "Personas Bloqueadas Frontend Dev",
                      "params": {
                        "url": "http://pb-front-dev-argo-app-lista-personas-bloqueadas-frontend-dev.admin-fin.svc.cluster.local:8080/"
                      }
                    }
                  ]
                }