nameOverride: ""
fullnameOverride: ""
extraLabels:
  - app: saldo-diario-services
  - env: dev
  - component: backend
crnamespace: openshift-gitops
app:
  destination:
    namespace: saldo-diario
    server: 'https://kubernetes.default.svc'
  project: default
  type: helm
  autosync: true
  helm:
    chart: portales
    url: http://20.118.83.132:8081/repository/helm/
    revision: 0.1.11
    values:
        nameOverride: ""
        routeHostOverride: saldo-diario-dev.apps.oxzaromdp01.southcentralus.aroapp.io
        routePathPrefix: /saldodiarioapiV2/api
        # livenessProbe: 
        #   tcpSocket:
        #     port: 8080
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 20
        #   periodSeconds: 10
        #   successThreshold: 1
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /botonapiV2/actuator/health
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 20
        #   periodSeconds: 30
        #   successThreshold: 1
        #   failureThreshold: 3
        envFrom:
        - secretRef:
            name: saldo-diario-services-secrets
        image:
          repository: oxzacrmdps01.azurecr.io/oxzacrmdps01/saldo-diario-services
        replicaCount: 1
        serviceAccount:
          name: "default"
        extraLabels:
          - app.openshift.io/runtime: spring-boot
          - app.kubernetes.io/part-of: saldo-diario-services
          - app.openshift.io/part-off: saldo-diario-services
          - portal: saldo-diario
          - env: dev
          - component: backend
        containerVolumes:
          create: true
          list:
          - type: inline-secret-store
            name: secrets-store-inline
            readOnly: true
            path: /mnt/secrets-store
            secretProviderClass: pb-azure-kv
            secretProviderCreds: saldo-diario-services-store-creds
        configmaps:
          list: []
        secrets:
          create: true
          createProvider: true
          list: []
          providerRefs:
          - objName: OXZKVSD-SD-FCIAS-JDBC
            key: FCIAS_JDBC
          - objName: OXZKVSD-SD-FCIAS-XXFC-USR
            key: FCIAS_XXFC_USR
          - objName: OXZKVSD-SD-FCIAS-XXFC-PASS
            key: FCIAS_XXFC_PASS
          - objName: OXZKVSD-SD-DATABASE-DRIVER
            key: DATABASE_DRIVER
          - objName: OXZKVSD-SD-FCDAS-JDBC
            key: FCDAS_JDBC
          - objName: OXZKVSD-SD-FCDAS-WEBSALDO-USR
            key: FCDAS_WEBSALDO_USR
          - objName: OXZKVSD-SD-FCDAS-WEBSALDO-PASS
            key: FCDAS_WEBSALDO_USR
          - objName: OXZKVSD-SD-FCDAS-WEBSALDO-PASS
            key: FCDAS_WEBSALDO_PASS
          - objName: OXZKVSD-SD-SWAGGER-ENABLED
            key: SWAGGER_ENABLED
          - objName: OXZKVSD-SD-SHOW-SQL
            key: SHOW_SQL
          - objName: OXZKVSD-SD-HIBERNATE-FETCH-FIZE
            key: HIBERNATE_FETCH_FIZE
          providerSecretName: saldo-diario-services-secrets
          providerKeyvaultName: OXZKVMDPD01
          providerClassName: pb-azure-kv
        imagePullSecrets:
          create: true
          list: 
          - name: azure-cr
        resources: 
          limits:
            cpu: "1"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "4Gi"
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 3
          targetMemoryUtilizationPercentage: 80
