nameOverride: ""
fullnameOverride: "k8s-secrets-store-csi"
extraLabels:
  - app: csi
  - env: infra-prod
crnamespace: openshift-gitops
app:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  autosync: true
  type: helm
  helm:
    chart: helm-infra
    url: 'http://20.118.83.132:8081/repository/helm/' # nexus
    revision: 0.0.5
    values:
      project:
        create: true
        name: "k8s-secrets-store-csi"
        display: "k8s-secrets-store-csi"
        privileged: false
      roles:
        create: true
        list:
        - name: secret-create
          extraLabels:
            app: k8s-secrets-store
          rules:
          - verbs:
              - '*'
            apiGroups:
              - ''
            resources:
              - secrets
        - name: secret-list
          extraLabels:
            app: k8s-secrets-store
          rules:
          - verbs:
              - list
            apiGroups:
              - ''
            resources:
              - secrets
      bindings:
        create: true
        list:
        - name: list-secrets-driver
          namespace: ""
          local: false
          extraLabels:
            app: k8s-secrets-store
          subjects:
          - kind: ServiceAccount
            name: secrets-store-csi-driver
            namespace: k8s-secrets-store-csi
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: secret-list
        - name: secret-storecsi-privileged
          namespace: ""
          local: false
          extraLabels:
            app: k8s-secrets-store
          subjects:
          - kind: ServiceAccount
            name: secrets-store-csi-driver
            namespace: k8s-secrets-store-csi
          - kind: ServiceAccount
            name: csi-secrets-store-provider-azure
            namespace: k8s-secrets-store-csi
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: system:openshift:scc:privileged