nameOverride: ""
fullnameOverride: "csi-secrets-store"
extraLabels:
  - app: csi
  - env: infra-prod
crnamespace: openshift-gitops
app:
  destination:
    namespace: k8s-secrets-store-csi
    server: 'https://kubernetes.default.svc'
  project: default
  type: helm
  autosync: true
  helm:
    chart: secrets-store-csi-driver
    revision: 1.4.5
    url: 'https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts'
    values:
      linux:
        privileged: true
        providersDir: /var/run/secrets-store-csi-providers
      secrets-store-csi-driver:
        enableSecretRotation: true
        rotationPollInterval: 24h
        syncSecret:
          enabled: true