nameOverride: ""
fullnameOverride: ""
extraLabels:
  - app: reportes-cnt
  - env: qa
crnamespace: openshift-gitops
app:
  destination:
    namespace: admin-fin-qa
    server: 'https://kubernetes.default.svc'
  project: default
  type: helm
  helm:
    chart: portales
    url: http://20.118.83.132:8081/repository/helm/
    revision: 0.1.9
    values:
        nameOverride: "reportes-cnt-frontend-qa"
        routeHostOverride: reportes-cnt-frontend-qa-admin-fin-qa.apps.oxzaromdp01.southcentralus.aroapp.io
        image:
          repository: oxzacrmdps01.azurecr.io/oxzacrmdps01/reportes-cnt-front
          tag: qa
        replicaCount: 2
        livenessProbe: 
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        readinessProbe: 
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        # horizontalPodAutoscaler:
        #   create: true
        #   minReplicas: 2
        #   maxReplicas: 4
        #   metrics:
        #   - type: Resource
        #     resource:
        #       name: cpu
        #       target:
        #         averageUtilization: 70
        #         type: Utilization
        serviceAccount:
          name: "default"
        extraLabels:
          - app.openshift.io/runtime: nginx
          - app.kubernetes.io/part-of: reportes-cnt
          - app.openshift.io/part-off: reportes-cnt