app:
  helm:
    params:
      - name: image.tag
        value: %FINAL_TAG%
      - name: secrets.list[0].name
        value: pb-secrets-store-creds
      - name: secrets.list[0].type
        value: Opaque
      # - name: 'secrets.list[0].extraLabels.secrets-store.csi.k8s.io/used'
      #   value: "true"
      - name: secrets.list[0].stringData.clientid
        value: %JAR_AZURE_KEYVAULT_CLIENTID_PROD%
      - name: secrets.list[0].stringData.clientsecret
        value: %JAR_AZURE_KEYVAULT_CLIENTSECRET_PROD%
      - name: secrets.providerTenant
        value: %JAR_AZURE_KEYVAULT_TENANTID_PROD%