{{- $dot := . }}
{{- if .Values.secrets.create }}
{{- range $s := .Values.secrets.list }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $s.name }}
  namespace: {{ $s.namespace }}
  labels:
    app.kubernetes.io/version: {{ $dot.Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ $dot.Release.Service }}
    app.kubernetes.io/name: {{ default $dot.Chart.Name $dot.Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ $dot.Release.Name }}
    meta.helm.sh/release-namespace: {{ $dot.Release.Namespace }}
    {{- with $s.extraLabels }}
      {{ toYaml . | nindent 4 }}
    {{- end}}
{{- with $s.data }}
data:
{{- toYaml . | nindent 2 }}
{{- end}}
{{- with $s.stringData }}
stringData:
{{- toYaml . | nindent 2 }}
{{- end}}
type: {{ $s.type }}
{{- end }}
{{- end }}