{{- $dot := . }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  {{- if .Values.serviceAccount.local }}
  namespace: {{ .Values.serviceAccount.namespace }}
  {{- end }}
# secrets
{{- if .Values.secrets.create }}
secrets:
{{- range $s := .Values.secrets.list }}

{{- if $s.assignSecret }}
  - name: {{ $s.name }}
{{- end }} #end if assign

{{- end }} #end range
{{- end }} #end if create secr

# pullsecrets
{{- if .Values.secrets.create }}
imagePullSecrets:
{{- range $s := .Values.secrets.list }}

{{- if $s.assignPull }}
  - name: {{ $s.name }}
{{- end }} #end if assign

{{- end }} #end range
{{- end }} #end if create ps

{{- end }} #end if create sa