name: Checkmarx Workflow - [Test]
on:
  workflow_call:
    inputs:
      workflows-ref:
        required: true
        type: string      
      tags:
        required: true
        type: string
      threshold:
        required: true
        type: string
    secrets:
      cx_client_id:
        required: true
      cx_client_secret:
        required: true
jobs:
  setup-settings:
    runs-on: ubuntu-latest
    steps:
      - name: "Configuración inicial"
        run: echo "si establece configuración inicial"
  build:
    runs-on: ubuntu-latest
    needs: [setup-settings]
    steps:      
      - name: Checkmarx
        uses: BUS-BackOffice/BO_Pipelines/.github/actions/checkmarx@main
        with:
          cx_client_id: ${{ secrets.cx_client_id }}
          cx_client_secret: ${{ secrets.cx_client_secret }}
          tags: ${{ inputs.tags }}
          threshold: ${{ inputs.threshold }}
