name: Workflow Environment
on:
  workflow_call:
    inputs:
      ref_name:
        description: "Git Branch"
        required: true
        type: string
      run_unit_tests:
        description: "Run unit tests"
        required: false
        type: string
    outputs:
      current: 
        description: "Current Environment"
        value: ${{ jobs.prepare.outputs.current }}
      previous: 
        description: "Previous Environment"
        value: ${{ jobs.prepare.outputs.previous }}
      run-unit-tests:
        description: "Run unit tests"
        value: ${{ jobs.prepare.outputs.runtests }}
      dir:
        description: "Directory"
        value: ${{ jobs.prepare.outputs.dir }}
permissions: write-all
jobs:
  prepare:
    outputs:
      current: ${{ steps.prepare.outputs.current }}
      previous: ${{ steps.prepare.outputs.previous }}
      runtests: ${{ steps.prepare.outputs.runtests }}
      dir: ${{ steps.prepare.outputs.dir }}
    runs-on: ubuntu-latest
    steps:
    - id: prepare
      run: |
        
        # unittestss
        if [ -z "${{ inputs.run_unit_tests }}" ]; then
          echo "runtests=false" >> $GITHUB_OUTPUT;
        else
          echo "runtests=${{ inputs.run_unit_tests }}" >> $GITHUB_OUTPUT;
        fi

        echo "${{ inputs.ref_name }}"
        if [ "${{ inputs.ref_name }}" = "main" ]; then
          echo "current=prod" >> $GITHUB_OUTPUT;
          echo "dir=prod" >> $GITHUB_OUTPUT;
          echo "previous=qa" >> $GITHUB_OUTPUT;
        elif [ "${{ inputs.ref_name }}" = "staging" ]; then
          echo "current=qa" >> $GITHUB_OUTPUT;
          echo "dir=qa" >> $GITHUB_OUTPUT;
          echo "previous=dev" >> $GITHUB_OUTPUT;
        elif [ "${{ inputs.ref_name }}" = "develop" ]; then
          echo "current=dev" >> $GITHUB_OUTPUT;
          echo "dir=dev" >> $GITHUB_OUTPUT;
          echo "previous='feat'" >> $GITHUB_OUTPUT;
        else
          echo "current=feat" >> $GITHUB_OUTPUT;
          echo "dir=dev" >> $GITHUB_OUTPUT;
          echo "previous=''" >> $GITHUB_OUTPUT;
        fi
